### PR TITLE
Add User and WorkItem

### PR DESCRIPTION
**Pull request by ruby232**
Add new endpoints User and WorkItem

### CODE REVIEW

**Comment by doishub** [comment]
Thanks for contributing and adding new endpoints! I've cleaned up the files a bit.

**Comment by ruby232** [comment]
@doishub Something is missing to merge this ?

**Comment by doishub** [comment]
Could you please answer the question in the review? I still don't see the reason why the `query` method was included. Perhaps you could give me a small example?

**Comment by ruby232** [comment]
For example, to access all of a user's items on a given date

```php
    return $this->client->workItems()
      ->fields(['id', 'author(id)', 'issue(id,customFields(name,value(name)))', 'date', 'duration(presentation,minutes)'])
      ->query('startDate', $startDate)
      ->query('endDate', $endDate)
      ->query('author', $userId)
      ->all();
```

**Comment by doishub** [comment]
I understand. It could be that this will be changed again in version 1.0, as the method could also be used by other endpoints.

I will adopt it for now, thanks for your contribution. If you can, it would be great if you could open a separate PR for the documentation.

**Pull request merged**
